### PR TITLE
Fix deprecation warnings for PHP 8.2

### LINKED ISSUE #147: Deprecated warnings in PHP 8.2
**Describe the bug**
Currently the code is producing deprecation warnings when running on PHP 8.2

**To Reproduce**
For example run the unit tests via `vendor/bin/phpunit --filter=courseformatrenderer_test`. You will see:
```
Deprecated: Creation of dynamic property section_info::$toggle is deprecated in /var/www/html/course/format/topcoll/tests/courseformatrenderer_test.php on line 465

Deprecated: Creation of dynamic property section_info::$toggle is deprecated in /var/www/html/course/format/topcoll/classes/output/renderer.php on line 913

Deprecated: Creation of dynamic property section_info::$isshown is deprecated in /var/www/html/course/format/topcoll/classes/output/renderer.php on line 922
```

**Expected behaviour**
No deprecation warnings.

 - Moodle: 4.3.3
 - Format: latest main
 - Browser and version [e.g. Chrome Version 108.0.5359.125 (Official Build) (64-bit) on Windows 10] Does not depend on the browser

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #147

### CODE REVIEW

File: classes/output/renderer.php [hunk 1]
```diff
@@ -471,10 +471,8 @@ protected function topcoll_section($section, $course, $onsectionpage, $sectionre
             $this->toggle_icon_set($sectioncontext);
             $sectioncontext['toggleiconsize'] = $this->tctoggleiconsize;
 
-            if ((!($section->toggle === null)) && ($section->toggle == true)) {
-                $sectioncontext['toggleopen'] = true;
-            } else {
-                $sectioncontext['toggleopen'] = false;
+            if (!is_null($toggle)) {
```
Comment (gjb2048) [inline classes/output/renderer.php]: Missing setting of $sectioncontext['toggleopen'] = false; if '$toggle' is null.

Comment (PhMemmel) [reply classes/output/renderer.php]: Yes, I read the logic wrong in the first place, fixed!
